/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AutoIzYaponiiRouteImport } from './routes/auto-iz-yaponii'
import { Route as AutoIzSshaRouteImport } from './routes/auto-iz-ssha'
import { Route as AutoIzKoreiRouteImport } from './routes/auto-iz-korei'
import { Route as AutoIzKitayaRouteImport } from './routes/auto-iz-kitaya'
import { Route as AutoIzEvropyRouteImport } from './routes/auto-iz-evropy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UslugiRastamozhkaAvtoRouteImport } from './routes/uslugi.rastamozhka-avto'
import { Route as UslugiProverkaAvtoRouteImport } from './routes/uslugi.proverka-avto'
import { Route as UslugiPokupkaAvtoNaAuktsioneYaponiiRouteImport } from './routes/uslugi.pokupka-avto-na-auktsione-yaponii'
import { Route as UslugiPodborAvtoRouteImport } from './routes/uslugi.podbor-avto'
import { Route as UslugiParallelnyyImportAvtoRouteImport } from './routes/uslugi.parallelnyy-import-avto'
import { Route as UslugiDostavkaIRastamozhkaRouteImport } from './routes/uslugi.dostavka-i-rastamozhka'
import { Route as UslugiAvtoPodZakazRouteImport } from './routes/uslugi.avto-pod-zakaz'
import { Route as UslugiAvtoIzZaRubezhaRouteImport } from './routes/uslugi.avto-iz-za-rubezha'
import { Route as RegionVladivostokRouteImport } from './routes/region.vladivostok'
import { Route as RegionSanktPeterburgRouteImport } from './routes/region.sankt-peterburg'
import { Route as RegionNovosibirskRouteImport } from './routes/region.novosibirsk'
import { Route as RegionMoskvaRouteImport } from './routes/region.moskva'
import { Route as RegionKrasnoyarskRouteImport } from './routes/region.krasnoyarsk'
import { Route as RegionIrkutskRouteImport } from './routes/region.irkutsk'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoIzYaponiiRoute = AutoIzYaponiiRouteImport.update({
  id: '/auto-iz-yaponii',
  path: '/auto-iz-yaponii',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoIzSshaRoute = AutoIzSshaRouteImport.update({
  id: '/auto-iz-ssha',
  path: '/auto-iz-ssha',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoIzKoreiRoute = AutoIzKoreiRouteImport.update({
  id: '/auto-iz-korei',
  path: '/auto-iz-korei',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoIzKitayaRoute = AutoIzKitayaRouteImport.update({
  id: '/auto-iz-kitaya',
  path: '/auto-iz-kitaya',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoIzEvropyRoute = AutoIzEvropyRouteImport.update({
  id: '/auto-iz-evropy',
  path: '/auto-iz-evropy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiRastamozhkaAvtoRoute = UslugiRastamozhkaAvtoRouteImport.update({
  id: '/uslugi/rastamozhka-avto',
  path: '/uslugi/rastamozhka-avto',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiProverkaAvtoRoute = UslugiProverkaAvtoRouteImport.update({
  id: '/uslugi/proverka-avto',
  path: '/uslugi/proverka-avto',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiPokupkaAvtoNaAuktsioneYaponiiRoute =
  UslugiPokupkaAvtoNaAuktsioneYaponiiRouteImport.update({
    id: '/uslugi/pokupka-avto-na-auktsione-yaponii',
    path: '/uslugi/pokupka-avto-na-auktsione-yaponii',
    getParentRoute: () => rootRouteImport,
  } as any)
const UslugiPodborAvtoRoute = UslugiPodborAvtoRouteImport.update({
  id: '/uslugi/podbor-avto',
  path: '/uslugi/podbor-avto',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiParallelnyyImportAvtoRoute =
  UslugiParallelnyyImportAvtoRouteImport.update({
    id: '/uslugi/parallelnyy-import-avto',
    path: '/uslugi/parallelnyy-import-avto',
    getParentRoute: () => rootRouteImport,
  } as any)
const UslugiDostavkaIRastamozhkaRoute =
  UslugiDostavkaIRastamozhkaRouteImport.update({
    id: '/uslugi/dostavka-i-rastamozhka',
    path: '/uslugi/dostavka-i-rastamozhka',
    getParentRoute: () => rootRouteImport,
  } as any)
const UslugiAvtoPodZakazRoute = UslugiAvtoPodZakazRouteImport.update({
  id: '/uslugi/avto-pod-zakaz',
  path: '/uslugi/avto-pod-zakaz',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiAvtoIzZaRubezhaRoute = UslugiAvtoIzZaRubezhaRouteImport.update({
  id: '/uslugi/avto-iz-za-rubezha',
  path: '/uslugi/avto-iz-za-rubezha',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionVladivostokRoute = RegionVladivostokRouteImport.update({
  id: '/region/vladivostok',
  path: '/region/vladivostok',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSanktPeterburgRoute = RegionSanktPeterburgRouteImport.update({
  id: '/region/sankt-peterburg',
  path: '/region/sankt-peterburg',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionNovosibirskRoute = RegionNovosibirskRouteImport.update({
  id: '/region/novosibirsk',
  path: '/region/novosibirsk',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionMoskvaRoute = RegionMoskvaRouteImport.update({
  id: '/region/moskva',
  path: '/region/moskva',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionKrasnoyarskRoute = RegionKrasnoyarskRouteImport.update({
  id: '/region/krasnoyarsk',
  path: '/region/krasnoyarsk',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionIrkutskRoute = RegionIrkutskRouteImport.update({
  id: '/region/irkutsk',
  path: '/region/irkutsk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-iz-evropy': typeof AutoIzEvropyRoute
  '/auto-iz-kitaya': typeof AutoIzKitayaRoute
  '/auto-iz-korei': typeof AutoIzKoreiRoute
  '/auto-iz-ssha': typeof AutoIzSshaRoute
  '/auto-iz-yaponii': typeof AutoIzYaponiiRoute
  '/crm': typeof CrmRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/region/irkutsk': typeof RegionIrkutskRoute
  '/region/krasnoyarsk': typeof RegionKrasnoyarskRoute
  '/region/moskva': typeof RegionMoskvaRoute
  '/region/novosibirsk': typeof RegionNovosibirskRoute
  '/region/sankt-peterburg': typeof RegionSanktPeterburgRoute
  '/region/vladivostok': typeof RegionVladivostokRoute
  '/uslugi/avto-iz-za-rubezha': typeof UslugiAvtoIzZaRubezhaRoute
  '/uslugi/avto-pod-zakaz': typeof UslugiAvtoPodZakazRoute
  '/uslugi/dostavka-i-rastamozhka': typeof UslugiDostavkaIRastamozhkaRoute
  '/uslugi/parallelnyy-import-avto': typeof UslugiParallelnyyImportAvtoRoute
  '/uslugi/podbor-avto': typeof UslugiPodborAvtoRoute
  '/uslugi/pokupka-avto-na-auktsione-yaponii': typeof UslugiPokupkaAvtoNaAuktsioneYaponiiRoute
  '/uslugi/proverka-avto': typeof UslugiProverkaAvtoRoute
  '/uslugi/rastamozhka-avto': typeof UslugiRastamozhkaAvtoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-iz-evropy': typeof AutoIzEvropyRoute
  '/auto-iz-kitaya': typeof AutoIzKitayaRoute
  '/auto-iz-korei': typeof AutoIzKoreiRoute
  '/auto-iz-ssha': typeof AutoIzSshaRoute
  '/auto-iz-yaponii': typeof AutoIzYaponiiRoute
  '/crm': typeof CrmRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/region/irkutsk': typeof RegionIrkutskRoute
  '/region/krasnoyarsk': typeof RegionKrasnoyarskRoute
  '/region/moskva': typeof RegionMoskvaRoute
  '/region/novosibirsk': typeof RegionNovosibirskRoute
  '/region/sankt-peterburg': typeof RegionSanktPeterburgRoute
  '/region/vladivostok': typeof RegionVladivostokRoute
  '/uslugi/avto-iz-za-rubezha': typeof UslugiAvtoIzZaRubezhaRoute
  '/uslugi/avto-pod-zakaz': typeof UslugiAvtoPodZakazRoute
  '/uslugi/dostavka-i-rastamozhka': typeof UslugiDostavkaIRastamozhkaRoute
  '/uslugi/parallelnyy-import-avto': typeof UslugiParallelnyyImportAvtoRoute
  '/uslugi/podbor-avto': typeof UslugiPodborAvtoRoute
  '/uslugi/pokupka-avto-na-auktsione-yaponii': typeof UslugiPokupkaAvtoNaAuktsioneYaponiiRoute
  '/uslugi/proverka-avto': typeof UslugiProverkaAvtoRoute
  '/uslugi/rastamozhka-avto': typeof UslugiRastamozhkaAvtoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-iz-evropy': typeof AutoIzEvropyRoute
  '/auto-iz-kitaya': typeof AutoIzKitayaRoute
  '/auto-iz-korei': typeof AutoIzKoreiRoute
  '/auto-iz-ssha': typeof AutoIzSshaRoute
  '/auto-iz-yaponii': typeof AutoIzYaponiiRoute
  '/crm': typeof CrmRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/region/irkutsk': typeof RegionIrkutskRoute
  '/region/krasnoyarsk': typeof RegionKrasnoyarskRoute
  '/region/moskva': typeof RegionMoskvaRoute
  '/region/novosibirsk': typeof RegionNovosibirskRoute
  '/region/sankt-peterburg': typeof RegionSanktPeterburgRoute
  '/region/vladivostok': typeof RegionVladivostokRoute
  '/uslugi/avto-iz-za-rubezha': typeof UslugiAvtoIzZaRubezhaRoute
  '/uslugi/avto-pod-zakaz': typeof UslugiAvtoPodZakazRoute
  '/uslugi/dostavka-i-rastamozhka': typeof UslugiDostavkaIRastamozhkaRoute
  '/uslugi/parallelnyy-import-avto': typeof UslugiParallelnyyImportAvtoRoute
  '/uslugi/podbor-avto': typeof UslugiPodborAvtoRoute
  '/uslugi/pokupka-avto-na-auktsione-yaponii': typeof UslugiPokupkaAvtoNaAuktsioneYaponiiRoute
  '/uslugi/proverka-avto': typeof UslugiProverkaAvtoRoute
  '/uslugi/rastamozhka-avto': typeof UslugiRastamozhkaAvtoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auto-iz-evropy'
    | '/auto-iz-kitaya'
    | '/auto-iz-korei'
    | '/auto-iz-ssha'
    | '/auto-iz-yaponii'
    | '/crm'
    | '/privacy'
    | '/sitemap.xml'
    | '/region/irkutsk'
    | '/region/krasnoyarsk'
    | '/region/moskva'
    | '/region/novosibirsk'
    | '/region/sankt-peterburg'
    | '/region/vladivostok'
    | '/uslugi/avto-iz-za-rubezha'
    | '/uslugi/avto-pod-zakaz'
    | '/uslugi/dostavka-i-rastamozhka'
    | '/uslugi/parallelnyy-import-avto'
    | '/uslugi/podbor-avto'
    | '/uslugi/pokupka-avto-na-auktsione-yaponii'
    | '/uslugi/proverka-avto'
    | '/uslugi/rastamozhka-avto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auto-iz-evropy'
    | '/auto-iz-kitaya'
    | '/auto-iz-korei'
    | '/auto-iz-ssha'
    | '/auto-iz-yaponii'
    | '/crm'
    | '/privacy'
    | '/sitemap.xml'
    | '/region/irkutsk'
    | '/region/krasnoyarsk'
    | '/region/moskva'
    | '/region/novosibirsk'
    | '/region/sankt-peterburg'
    | '/region/vladivostok'
    | '/uslugi/avto-iz-za-rubezha'
    | '/uslugi/avto-pod-zakaz'
    | '/uslugi/dostavka-i-rastamozhka'
    | '/uslugi/parallelnyy-import-avto'
    | '/uslugi/podbor-avto'
    | '/uslugi/pokupka-avto-na-auktsione-yaponii'
    | '/uslugi/proverka-avto'
    | '/uslugi/rastamozhka-avto'
  id:
    | '__root__'
    | '/'
    | '/auto-iz-evropy'
    | '/auto-iz-kitaya'
    | '/auto-iz-korei'
    | '/auto-iz-ssha'
    | '/auto-iz-yaponii'
    | '/crm'
    | '/privacy'
    | '/sitemap.xml'
    | '/region/irkutsk'
    | '/region/krasnoyarsk'
    | '/region/moskva'
    | '/region/novosibirsk'
    | '/region/sankt-peterburg'
    | '/region/vladivostok'
    | '/uslugi/avto-iz-za-rubezha'
    | '/uslugi/avto-pod-zakaz'
    | '/uslugi/dostavka-i-rastamozhka'
    | '/uslugi/parallelnyy-import-avto'
    | '/uslugi/podbor-avto'
    | '/uslugi/pokupka-avto-na-auktsione-yaponii'
    | '/uslugi/proverka-avto'
    | '/uslugi/rastamozhka-avto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoIzEvropyRoute: typeof AutoIzEvropyRoute
  AutoIzKitayaRoute: typeof AutoIzKitayaRoute
  AutoIzKoreiRoute: typeof AutoIzKoreiRoute
  AutoIzSshaRoute: typeof AutoIzSshaRoute
  AutoIzYaponiiRoute: typeof AutoIzYaponiiRoute
  CrmRoute: typeof CrmRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RegionIrkutskRoute: typeof RegionIrkutskRoute
  RegionKrasnoyarskRoute: typeof RegionKrasnoyarskRoute
  RegionMoskvaRoute: typeof RegionMoskvaRoute
  RegionNovosibirskRoute: typeof RegionNovosibirskRoute
  RegionSanktPeterburgRoute: typeof RegionSanktPeterburgRoute
  RegionVladivostokRoute: typeof RegionVladivostokRoute
  UslugiAvtoIzZaRubezhaRoute: typeof UslugiAvtoIzZaRubezhaRoute
  UslugiAvtoPodZakazRoute: typeof UslugiAvtoPodZakazRoute
  UslugiDostavkaIRastamozhkaRoute: typeof UslugiDostavkaIRastamozhkaRoute
  UslugiParallelnyyImportAvtoRoute: typeof UslugiParallelnyyImportAvtoRoute
  UslugiPodborAvtoRoute: typeof UslugiPodborAvtoRoute
  UslugiPokupkaAvtoNaAuktsioneYaponiiRoute: typeof UslugiPokupkaAvtoNaAuktsioneYaponiiRoute
  UslugiProverkaAvtoRoute: typeof UslugiProverkaAvtoRoute
  UslugiRastamozhkaAvtoRoute: typeof UslugiRastamozhkaAvtoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-iz-yaponii': {
      id: '/auto-iz-yaponii'
      path: '/auto-iz-yaponii'
      fullPath: '/auto-iz-yaponii'
      preLoaderRoute: typeof AutoIzYaponiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-iz-ssha': {
      id: '/auto-iz-ssha'
      path: '/auto-iz-ssha'
      fullPath: '/auto-iz-ssha'
      preLoaderRoute: typeof AutoIzSshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-iz-korei': {
      id: '/auto-iz-korei'
      path: '/auto-iz-korei'
      fullPath: '/auto-iz-korei'
      preLoaderRoute: typeof AutoIzKoreiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-iz-kitaya': {
      id: '/auto-iz-kitaya'
      path: '/auto-iz-kitaya'
      fullPath: '/auto-iz-kitaya'
      preLoaderRoute: typeof AutoIzKitayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-iz-evropy': {
      id: '/auto-iz-evropy'
      path: '/auto-iz-evropy'
      fullPath: '/auto-iz-evropy'
      preLoaderRoute: typeof AutoIzEvropyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/rastamozhka-avto': {
      id: '/uslugi/rastamozhka-avto'
      path: '/uslugi/rastamozhka-avto'
      fullPath: '/uslugi/rastamozhka-avto'
      preLoaderRoute: typeof UslugiRastamozhkaAvtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/proverka-avto': {
      id: '/uslugi/proverka-avto'
      path: '/uslugi/proverka-avto'
      fullPath: '/uslugi/proverka-avto'
      preLoaderRoute: typeof UslugiProverkaAvtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/pokupka-avto-na-auktsione-yaponii': {
      id: '/uslugi/pokupka-avto-na-auktsione-yaponii'
      path: '/uslugi/pokupka-avto-na-auktsione-yaponii'
      fullPath: '/uslugi/pokupka-avto-na-auktsione-yaponii'
      preLoaderRoute: typeof UslugiPokupkaAvtoNaAuktsioneYaponiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/podbor-avto': {
      id: '/uslugi/podbor-avto'
      path: '/uslugi/podbor-avto'
      fullPath: '/uslugi/podbor-avto'
      preLoaderRoute: typeof UslugiPodborAvtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/parallelnyy-import-avto': {
      id: '/uslugi/parallelnyy-import-avto'
      path: '/uslugi/parallelnyy-import-avto'
      fullPath: '/uslugi/parallelnyy-import-avto'
      preLoaderRoute: typeof UslugiParallelnyyImportAvtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/dostavka-i-rastamozhka': {
      id: '/uslugi/dostavka-i-rastamozhka'
      path: '/uslugi/dostavka-i-rastamozhka'
      fullPath: '/uslugi/dostavka-i-rastamozhka'
      preLoaderRoute: typeof UslugiDostavkaIRastamozhkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/avto-pod-zakaz': {
      id: '/uslugi/avto-pod-zakaz'
      path: '/uslugi/avto-pod-zakaz'
      fullPath: '/uslugi/avto-pod-zakaz'
      preLoaderRoute: typeof UslugiAvtoPodZakazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/avto-iz-za-rubezha': {
      id: '/uslugi/avto-iz-za-rubezha'
      path: '/uslugi/avto-iz-za-rubezha'
      fullPath: '/uslugi/avto-iz-za-rubezha'
      preLoaderRoute: typeof UslugiAvtoIzZaRubezhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/vladivostok': {
      id: '/region/vladivostok'
      path: '/region/vladivostok'
      fullPath: '/region/vladivostok'
      preLoaderRoute: typeof RegionVladivostokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/sankt-peterburg': {
      id: '/region/sankt-peterburg'
      path: '/region/sankt-peterburg'
      fullPath: '/region/sankt-peterburg'
      preLoaderRoute: typeof RegionSanktPeterburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/novosibirsk': {
      id: '/region/novosibirsk'
      path: '/region/novosibirsk'
      fullPath: '/region/novosibirsk'
      preLoaderRoute: typeof RegionNovosibirskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/moskva': {
      id: '/region/moskva'
      path: '/region/moskva'
      fullPath: '/region/moskva'
      preLoaderRoute: typeof RegionMoskvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/krasnoyarsk': {
      id: '/region/krasnoyarsk'
      path: '/region/krasnoyarsk'
      fullPath: '/region/krasnoyarsk'
      preLoaderRoute: typeof RegionKrasnoyarskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/irkutsk': {
      id: '/region/irkutsk'
      path: '/region/irkutsk'
      fullPath: '/region/irkutsk'
      preLoaderRoute: typeof RegionIrkutskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoIzEvropyRoute: AutoIzEvropyRoute,
  AutoIzKitayaRoute: AutoIzKitayaRoute,
  AutoIzKoreiRoute: AutoIzKoreiRoute,
  AutoIzSshaRoute: AutoIzSshaRoute,
  AutoIzYaponiiRoute: AutoIzYaponiiRoute,
  CrmRoute: CrmRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RegionIrkutskRoute: RegionIrkutskRoute,
  RegionKrasnoyarskRoute: RegionKrasnoyarskRoute,
  RegionMoskvaRoute: RegionMoskvaRoute,
  RegionNovosibirskRoute: RegionNovosibirskRoute,
  RegionSanktPeterburgRoute: RegionSanktPeterburgRoute,
  RegionVladivostokRoute: RegionVladivostokRoute,
  UslugiAvtoIzZaRubezhaRoute: UslugiAvtoIzZaRubezhaRoute,
  UslugiAvtoPodZakazRoute: UslugiAvtoPodZakazRoute,
  UslugiDostavkaIRastamozhkaRoute: UslugiDostavkaIRastamozhkaRoute,
  UslugiParallelnyyImportAvtoRoute: UslugiParallelnyyImportAvtoRoute,
  UslugiPodborAvtoRoute: UslugiPodborAvtoRoute,
  UslugiPokupkaAvtoNaAuktsioneYaponiiRoute:
    UslugiPokupkaAvtoNaAuktsioneYaponiiRoute,
  UslugiProverkaAvtoRoute: UslugiProverkaAvtoRoute,
  UslugiRastamozhkaAvtoRoute: UslugiRastamozhkaAvtoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
